// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CdcAuthUsers is the predicate function for cdcauthusers builders.
type CdcAuthUsers func(*sql.Selector)

// StravaAccount is the predicate function for stravaaccount builders.
type StravaAccount func(*sql.Selector)
