// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/ngdangkietswe/swe-integration-service/data/ent/cdcauthusers"
	"github.com/ngdangkietswe/swe-integration-service/data/ent/predicate"
	"github.com/ngdangkietswe/swe-integration-service/data/ent/stravaactivity"
)

// StravaActivityQuery is the builder for querying StravaActivity entities.
type StravaActivityQuery struct {
	config
	ctx              *QueryContext
	order            []stravaactivity.OrderOption
	inters           []Interceptor
	predicates       []predicate.StravaActivity
	withCdcAuthUsers *CdcAuthUsersQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StravaActivityQuery builder.
func (saq *StravaActivityQuery) Where(ps ...predicate.StravaActivity) *StravaActivityQuery {
	saq.predicates = append(saq.predicates, ps...)
	return saq
}

// Limit the number of records to be returned by this query.
func (saq *StravaActivityQuery) Limit(limit int) *StravaActivityQuery {
	saq.ctx.Limit = &limit
	return saq
}

// Offset to start from.
func (saq *StravaActivityQuery) Offset(offset int) *StravaActivityQuery {
	saq.ctx.Offset = &offset
	return saq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (saq *StravaActivityQuery) Unique(unique bool) *StravaActivityQuery {
	saq.ctx.Unique = &unique
	return saq
}

// Order specifies how the records should be ordered.
func (saq *StravaActivityQuery) Order(o ...stravaactivity.OrderOption) *StravaActivityQuery {
	saq.order = append(saq.order, o...)
	return saq
}

// QueryCdcAuthUsers chains the current query on the "cdc_auth_users" edge.
func (saq *StravaActivityQuery) QueryCdcAuthUsers() *CdcAuthUsersQuery {
	query := (&CdcAuthUsersClient{config: saq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := saq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := saq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stravaactivity.Table, stravaactivity.FieldID, selector),
			sqlgraph.To(cdcauthusers.Table, cdcauthusers.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stravaactivity.CdcAuthUsersTable, stravaactivity.CdcAuthUsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(saq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StravaActivity entity from the query.
// Returns a *NotFoundError when no StravaActivity was found.
func (saq *StravaActivityQuery) First(ctx context.Context) (*StravaActivity, error) {
	nodes, err := saq.Limit(1).All(setContextOp(ctx, saq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stravaactivity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (saq *StravaActivityQuery) FirstX(ctx context.Context) *StravaActivity {
	node, err := saq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StravaActivity ID from the query.
// Returns a *NotFoundError when no StravaActivity ID was found.
func (saq *StravaActivityQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = saq.Limit(1).IDs(setContextOp(ctx, saq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stravaactivity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (saq *StravaActivityQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := saq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StravaActivity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StravaActivity entity is found.
// Returns a *NotFoundError when no StravaActivity entities are found.
func (saq *StravaActivityQuery) Only(ctx context.Context) (*StravaActivity, error) {
	nodes, err := saq.Limit(2).All(setContextOp(ctx, saq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stravaactivity.Label}
	default:
		return nil, &NotSingularError{stravaactivity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (saq *StravaActivityQuery) OnlyX(ctx context.Context) *StravaActivity {
	node, err := saq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StravaActivity ID in the query.
// Returns a *NotSingularError when more than one StravaActivity ID is found.
// Returns a *NotFoundError when no entities are found.
func (saq *StravaActivityQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = saq.Limit(2).IDs(setContextOp(ctx, saq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stravaactivity.Label}
	default:
		err = &NotSingularError{stravaactivity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (saq *StravaActivityQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := saq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StravaActivities.
func (saq *StravaActivityQuery) All(ctx context.Context) ([]*StravaActivity, error) {
	ctx = setContextOp(ctx, saq.ctx, ent.OpQueryAll)
	if err := saq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StravaActivity, *StravaActivityQuery]()
	return withInterceptors[[]*StravaActivity](ctx, saq, qr, saq.inters)
}

// AllX is like All, but panics if an error occurs.
func (saq *StravaActivityQuery) AllX(ctx context.Context) []*StravaActivity {
	nodes, err := saq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StravaActivity IDs.
func (saq *StravaActivityQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if saq.ctx.Unique == nil && saq.path != nil {
		saq.Unique(true)
	}
	ctx = setContextOp(ctx, saq.ctx, ent.OpQueryIDs)
	if err = saq.Select(stravaactivity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (saq *StravaActivityQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := saq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (saq *StravaActivityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, saq.ctx, ent.OpQueryCount)
	if err := saq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, saq, querierCount[*StravaActivityQuery](), saq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (saq *StravaActivityQuery) CountX(ctx context.Context) int {
	count, err := saq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (saq *StravaActivityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, saq.ctx, ent.OpQueryExist)
	switch _, err := saq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (saq *StravaActivityQuery) ExistX(ctx context.Context) bool {
	exist, err := saq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StravaActivityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (saq *StravaActivityQuery) Clone() *StravaActivityQuery {
	if saq == nil {
		return nil
	}
	return &StravaActivityQuery{
		config:           saq.config,
		ctx:              saq.ctx.Clone(),
		order:            append([]stravaactivity.OrderOption{}, saq.order...),
		inters:           append([]Interceptor{}, saq.inters...),
		predicates:       append([]predicate.StravaActivity{}, saq.predicates...),
		withCdcAuthUsers: saq.withCdcAuthUsers.Clone(),
		// clone intermediate query.
		sql:  saq.sql.Clone(),
		path: saq.path,
	}
}

// WithCdcAuthUsers tells the query-builder to eager-load the nodes that are connected to
// the "cdc_auth_users" edge. The optional arguments are used to configure the query builder of the edge.
func (saq *StravaActivityQuery) WithCdcAuthUsers(opts ...func(*CdcAuthUsersQuery)) *StravaActivityQuery {
	query := (&CdcAuthUsersClient{config: saq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	saq.withCdcAuthUsers = query
	return saq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StravaActivityID int64 `json:"strava_activity_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StravaActivity.Query().
//		GroupBy(stravaactivity.FieldStravaActivityID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (saq *StravaActivityQuery) GroupBy(field string, fields ...string) *StravaActivityGroupBy {
	saq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StravaActivityGroupBy{build: saq}
	grbuild.flds = &saq.ctx.Fields
	grbuild.label = stravaactivity.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		StravaActivityID int64 `json:"strava_activity_id,omitempty"`
//	}
//
//	client.StravaActivity.Query().
//		Select(stravaactivity.FieldStravaActivityID).
//		Scan(ctx, &v)
func (saq *StravaActivityQuery) Select(fields ...string) *StravaActivitySelect {
	saq.ctx.Fields = append(saq.ctx.Fields, fields...)
	sbuild := &StravaActivitySelect{StravaActivityQuery: saq}
	sbuild.label = stravaactivity.Label
	sbuild.flds, sbuild.scan = &saq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StravaActivitySelect configured with the given aggregations.
func (saq *StravaActivityQuery) Aggregate(fns ...AggregateFunc) *StravaActivitySelect {
	return saq.Select().Aggregate(fns...)
}

func (saq *StravaActivityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range saq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, saq); err != nil {
				return err
			}
		}
	}
	for _, f := range saq.ctx.Fields {
		if !stravaactivity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if saq.path != nil {
		prev, err := saq.path(ctx)
		if err != nil {
			return err
		}
		saq.sql = prev
	}
	return nil
}

func (saq *StravaActivityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StravaActivity, error) {
	var (
		nodes       = []*StravaActivity{}
		_spec       = saq.querySpec()
		loadedTypes = [1]bool{
			saq.withCdcAuthUsers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StravaActivity).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StravaActivity{config: saq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, saq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := saq.withCdcAuthUsers; query != nil {
		if err := saq.loadCdcAuthUsers(ctx, query, nodes, nil,
			func(n *StravaActivity, e *CdcAuthUsers) { n.Edges.CdcAuthUsers = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (saq *StravaActivityQuery) loadCdcAuthUsers(ctx context.Context, query *CdcAuthUsersQuery, nodes []*StravaActivity, init func(*StravaActivity), assign func(*StravaActivity, *CdcAuthUsers)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*StravaActivity)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(cdcauthusers.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (saq *StravaActivityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := saq.querySpec()
	_spec.Node.Columns = saq.ctx.Fields
	if len(saq.ctx.Fields) > 0 {
		_spec.Unique = saq.ctx.Unique != nil && *saq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, saq.driver, _spec)
}

func (saq *StravaActivityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(stravaactivity.Table, stravaactivity.Columns, sqlgraph.NewFieldSpec(stravaactivity.FieldID, field.TypeUUID))
	_spec.From = saq.sql
	if unique := saq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if saq.path != nil {
		_spec.Unique = true
	}
	if fields := saq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stravaactivity.FieldID)
		for i := range fields {
			if fields[i] != stravaactivity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if saq.withCdcAuthUsers != nil {
			_spec.Node.AddColumnOnce(stravaactivity.FieldUserID)
		}
	}
	if ps := saq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := saq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := saq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := saq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (saq *StravaActivityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(saq.driver.Dialect())
	t1 := builder.Table(stravaactivity.Table)
	columns := saq.ctx.Fields
	if len(columns) == 0 {
		columns = stravaactivity.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if saq.sql != nil {
		selector = saq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if saq.ctx.Unique != nil && *saq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range saq.predicates {
		p(selector)
	}
	for _, p := range saq.order {
		p(selector)
	}
	if offset := saq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := saq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StravaActivityGroupBy is the group-by builder for StravaActivity entities.
type StravaActivityGroupBy struct {
	selector
	build *StravaActivityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sagb *StravaActivityGroupBy) Aggregate(fns ...AggregateFunc) *StravaActivityGroupBy {
	sagb.fns = append(sagb.fns, fns...)
	return sagb
}

// Scan applies the selector query and scans the result into the given value.
func (sagb *StravaActivityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sagb.build.ctx, ent.OpQueryGroupBy)
	if err := sagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StravaActivityQuery, *StravaActivityGroupBy](ctx, sagb.build, sagb, sagb.build.inters, v)
}

func (sagb *StravaActivityGroupBy) sqlScan(ctx context.Context, root *StravaActivityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sagb.fns))
	for _, fn := range sagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sagb.flds)+len(sagb.fns))
		for _, f := range *sagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StravaActivitySelect is the builder for selecting fields of StravaActivity entities.
type StravaActivitySelect struct {
	*StravaActivityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sas *StravaActivitySelect) Aggregate(fns ...AggregateFunc) *StravaActivitySelect {
	sas.fns = append(sas.fns, fns...)
	return sas
}

// Scan applies the selector query and scans the result into the given value.
func (sas *StravaActivitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sas.ctx, ent.OpQuerySelect)
	if err := sas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StravaActivityQuery, *StravaActivitySelect](ctx, sas.StravaActivityQuery, sas, sas.inters, v)
}

func (sas *StravaActivitySelect) sqlScan(ctx context.Context, root *StravaActivityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sas.fns))
	for _, fn := range sas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
